os: linux
dist: bionic

services: docker
compiler:
  - clang
  - gcc


before_install:
  - sudo apt-get install -y openssl libssl-dev
script:
- ./configure --enable-openssl --disable-x86asm
- make -j32
- sudo make install
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$REGISTRY"
- docker build -f push_cloud -t wajika/ffmpeg:latest .
