name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install openssl
      run: sudo apt-get install openssl
    - name: install libssl-dev
      run: sudo apt-get install libssl-dev
    - name: configure
      run: ./configure --enable-openssl --disable-x86asm
    - name: make
      run:  make -j32
    - name: make install
      run: sudo make install
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wajika/ffmpeg:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
		    dockerfile: push_cloud
