name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install openssl
      run: sudo apt-get install openssl
    - name: install libssl-dev
      run: sudo apt-get install libssl-dev
    - name: configure
      run: ./configure --enable-openssl --disable-x86asm
    - name: make
      run:  make -j32
    - name: make install
      run: sudo make install
    - uses: denverdino/acr-login@v1
      with:
        login-server: '<login server>'
        region-id: 'cn-hangzhou'
        access-key-id: 'LTAI4FcbNPgxVeSBoYzRFMRy'
        access-key-secret: 'dB9FmyEHbio7Q6k8wYI8oqXhs3m2PC'
    - name: Build the Docker image
      run: docker build . -f push_cloud -t registry.cn-hangzhou.aliyuncs.com/denverdino/ffmpeg:$(date +%s)
